### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mani1232** [DaRacci/slimjar#20]
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.github.slimjar.relocation.facade.ReflectiveJarRelocatorFacade.run(ReflectiveJarRelocatorFacade.java:41)
        at io.github.slimjar.relocation.JarFileRelocator.relocate(JarFileRelocator.java:49)
        at io.github.slimjar.relocation.helper.VerifyingRelocationHelper.relocate(VerifyingRelocationHelper.java:68)
        at io.github.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:63)
        at io.github.slimjar.injector.SimpleDependencyInjector.lambda$injectDependencies$1(SimpleDependencyInjector.java:67)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.github.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:62)
        at io.github.slimjar.injector.SimpleDependencyInjector.lambda$injectDependencies$1(SimpleDependencyInjector.java:72)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.github.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:62)
        at io.github.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:55)
        at io.github.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:65)
        at io.github.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:450)
        at ua.mani123.init.MainKt.main(Main.kt:7)
        at ua.mani123.init.MainKt.main(Main.kt)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
        at me.lucko.jarrelocator.JarRelocatorTask.processClass(JarRelocatorTask.java:164)
        at me.lucko.jarrelocator.JarRelocatorTask.processEntry(JarRelocatorTask.java:100)
        at me.lucko.jarrelocator.JarRelocatorTask.processEntries(JarRelocatorTask.java:87)
        at me.lucko.jarrelocator.JarRelocator.run(JarRelocator.java:89)
        ... 35 more
        ```

**Comment by mani1232** [comment]
Gradle kotlin dsl File
```gradle
plugins {
    kotlin("jvm") version "1.9.10"
    kotlin("plugin.serialization") version "1.9.10"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("dev.racci.slimjar") version "1.6.1"
}

group = "ua.mani123"
version = findProperty("version")!!
val projectName = findProperty("projectName")!!

repositories {
    mavenCentral()
    maven("https://maven.topi.wtf/releases")
    maven("https://oss.sonatype.org/content/repositories/snapshots")
    maven("https://jitpack.io/")
    maven("https://maven.arbjerg.dev/snapshots")
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://nexuslite.gcnt.net/repos/other/")
    maven("https://repo.racci.dev/releases/")
}

tasks.slimJar {
}

dependencies {
    slim("org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.6.0")
    slim("com.github.discord-jda:JDA:5.0.0-beta.13")
    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT")
    slim("com.charleskorn.kaml:kaml:0.55.0")
    slim("dev.arbjerg:lavaplayer:9c92cf39faedd5218b7e086e8ece13a21bff2f0a-SNAPSHOT") {
        exclude("commons-codec")
    }
    slim("com.github.topi314.lavasrc:lavasrc:3f26e2e")
    slim("org.bstats:bstats-base:3.0.2")
    slim("commons-codec:commons-codec:1.16.0")
    //implementation("com.jcabi:jcabi-manifests:2.1.0")
    slim("ch.qos.logback:logback-classic:1.4.11")
    slim("com.tcoded:FoliaLib:0.2.0")
    implementation("dev.racci.slimjar:slimjar:1.6.1")

    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.shadowJar {
    manifest {
        attributes(
            mapOf(
                "Specification-Title" to projectName,
                "Specification-Version" to version,
                "Specification-Vendor" to "WorldMandia",
                "Implementation-Title" to projectName,
                "Implementation-Version" to version,
                "Implementation-Vendor" to "WorldMandia",
                "Main-Class" to "ua.mani123.init.MainKt"
            )
        )
    }
    archiveFileName.set("$projectName-$version-all.jar")
    dependsOn(tasks.slimJar)
}

kotlin {
    jvmToolchain(17)
}

tasks {
    processResources {
        filesMatching(listOf("**plugin.yml")) {
            expand(mapOf(
                "projectVersion" to project.version,
                "projectName" to projectName
            ))
        }
    }
    javadoc {
        options.encoding = Charsets.UTF_8.toString()
    }
    compileJava {
        options.encoding = Charsets.UTF_8.toString()
    }
    compileTestJava {
        options.encoding = Charsets.UTF_8.toString()
    }
}
```

**Comment by DaRacci** [comment]
Seems like a java version miss-match, make sure you have compiled everything for java 17, i believe i encountered this a long time ago and had to change multiple gradle settings for it to actually work.
